version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@0x/order-utils"
    versions:
    - 10.4.15
    - 10.4.16
    - 10.4.17
    - 10.4.18
    - 10.4.19
  - dependency-name: "@0x/web3-wrapper"
    versions:
    - 7.4.1
    - 7.4.2
    - 7.4.3
    - 7.5.0
    - 7.5.2
  - dependency-name: "@0x/dev-utils"
    versions:
    - 4.2.1
    - 4.2.2
    - 4.2.3
    - 4.2.4
    - 4.2.6
  - dependency-name: "@0x/typescript-typings"
    versions:
    - 5.1.6
    - 5.1.7
  - dependency-name: "@0x/base-contract"
    versions:
    - 6.2.18
    - 6.2.19
    - 6.2.20
    - 6.3.0
    - 6.3.2
  - dependency-name: ethereum-types
    versions:
    - 3.4.0
    - 3.4.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
